export type Song = {
  id: string;
  title: string;
  /**
   * Fixed, hand-picked official YouTube video for this song. When present it
   * is used immediately at runtime — no discovery, no API. Songs without one
   * fall back to the searchQuery-based cache generated by `npm run
   * discover-songs`.
   */
  videoId?: string | undefined;
  searchQuery: string;
};

export type Playlist = {
  id: string;
  name: string;
  subtitle: string;
  songs: Song[];
};

export type DiscoveredVideo = {
  videoId: string;
  title: string;
  thumbnailUrl: string;
};

/**
 * These are searches, not video IDs. `npm run discover-songs` is the only
 * code that sends them to YouTube Data API v3 (one-time, offline); the result
 * is cached in youtube-cache.json and served statically at runtime.
 */
export const playlists: Playlist[] = [
  {
    id: "90s",
    name: "90s का सफ़र",
    subtitle: "Side A • धूल भरी सड़क",
    songs: [
      {
        id: "pehla-nasha",
        title: "Pehla Nasha",
        videoId: "SBfPs-PMGTA",
        searchQuery: "Pehla Nasha Jo Jeeta Wohi Sikandar",
      },
      {
        id: "tujhe-dekha-to",
        title: "Tujhe Dekha To",
        videoId: "cNV5hLSa9H8",
        searchQuery: "Tujhe Dekha To Dilwale Dulhania Le Jayenge",
      },
      {
        id: "ek-ladki-ko-dekha",
        title: "Ek Ladki Ko Dekha",
        videoId: "htMvfOfixuM",
        searchQuery: "Ek Ladki Ko Dekha To Aisa Laga",
      },
      {
        id: "do-dil-mil-rahe-hain",
        title: "Do Dil Mil Rahe Hain",
        searchQuery: "Do Dil Mil Rahe Hain Pardes",
      },
      {
        id: "aankhon-se-tune",
        title: "Aankhon Se Tune Kya Kehna Hai",
        videoId: "RlSRxyxFwXI",
        searchQuery: "Aankhon Se Tune Kya Kehna Hai",
      },
    ],
  },
];

export const destinations = [
  { hi: "लखनऊ", en: "LUCKNOW", fare: 42 },
  { hi: "कानपुर", en: "KANPUR", fare: 58 },
  { hi: "वाराणसी", en: "VARANASI", fare: 96 },
  { hi: "प्रयागराज", en: "PRAYAGRAJ", fare: 74 },
  { hi: "गोरखपुर", en: "GORAKHPUR", fare: 110 },
];
