import youtubeCacheJson from "./youtube-cache.json";
import { playlists, type DiscoveredVideo } from "./playlists";

/**
 * Static, pre-discovered YouTube results generated by `npm run discover-songs`.
 * Production playback reads this file only — it never calls the YouTube Data
 * API, so no search quota is consumed by visitors.
 */
export type YoutubeCache = {
  version: number;
  generatedAt: string;
  songs: Record<string, { candidates: DiscoveredVideo[] }>;
};

export const youtubeCache = youtubeCacheJson as YoutubeCache;

const thumbnailFor = (videoId: string) => `https://i.ytimg.com/vi/${videoId}/mqdefault.jpg`;

/**
 * Instant lookup of a song's playable candidates:
 *
 * 1. Songs with a hand-picked `videoId` in the playlist are returned directly
 *    (official video, no discovery, no API).
 * 2. Everything else comes from the static youtube-cache.json built by
 *    `npm run discover-songs`.
 */
export function getCachedCandidates(songId: string): DiscoveredVideo[] {
  const song = playlists.flatMap((playlist) => playlist.songs).find((item) => item.id === songId);
  if (song?.videoId) {
    return [
      {
        videoId: song.videoId,
        title: song.title,
        thumbnailUrl: thumbnailFor(song.videoId),
      },
    ];
  }
  return youtubeCache.songs[songId]?.candidates ?? [];
}
